// @platform/corpus-watch — shared types, paths, and helpers used by the
// scanner (watch.ts), the promoter (promote.ts), and the approve CLI.

import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));

export const CORPUS_DIR =
  process.env.CORPUS_DIR ?? resolve(HERE, "../../../../corpus");
export const SOURCES_PATH = resolve(CORPUS_DIR, "sources.seed.json");
export const STATE_PATH = resolve(CORPUS_DIR, ".corpus-watch-state.json");
export const QUEUE_JSON_PATH = resolve(CORPUS_DIR, "review-queue.json");
export const QUEUE_MD_PATH = resolve(CORPUS_DIR, "review-queue.md");

export type Platform = "youtube" | "instagram" | "tiktok" | "web";

// A corpus source. Many fields are optional here because the scanner only
// reads a handful; the promoter clones the full record from a parent creator.
export interface SourceRecord {
  title: string;
  url: string;
  source_name: string;
  source_tier?: string;
  topic?: string;
  age_band?: string;
  sport?: string;
  summary?: string;
  key_principles?: string[];
  safe_to_prescribe?: boolean;
  requires_guardrail?: boolean;
  guardrail_reason?: string;
  do_not_use_for?: string[];
  coach_use_case?: string;
  player_use_case?: string;
  parent_use_case?: string;
  practice_format?: string;
  equipment_needed?: string[];
  duration_minutes?: number | null;
  progression_level?: string;
  evidence_level?: string;
  tags?: string[];
}

export type CandidateStatus = "pending_review" | "approved" | "promoted";

export interface Candidate {
  id: string;
  discovered_at: string;
  status: CandidateStatus;
  platform: Platform;
  source_name: string;
  source_url: string;
  content_title: string;
  content_url: string;
  published_at?: string;
  needs_manual_check?: boolean;
  suggested_topic?: string;
  suggested_age_band?: string;
  suggested_tags: string[];
  note?: string;
  promoted_at?: string;
}

export function platformOf(url: string): Platform {
  const u = url.toLowerCase();
  if (u.includes("youtube.com") || u.includes("youtu.be")) return "youtube";
  if (u.includes("instagram.com")) return "instagram";
  if (u.includes("tiktok.com")) return "tiktok";
  return "web";
}

export function isCreatorSource(s: SourceRecord): boolean {
  const tags = (s.tags ?? []).map((t) => t.toLowerCase());
  if (tags.includes("social") || tags.includes("video")) return true;
  const p = platformOf(s.url);
  return p === "youtube" || p === "instagram" || p === "tiktok";
}

export function slug(s: string): string {
  return s
    .toLowerCase()
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
}

export async function loadJson<T>(path: string, fallback: T): Promise<T> {
  if (!existsSync(path)) return fallback;
  try {
    return JSON.parse(await readFile(path, "utf8")) as T;
  } catch (err) {
    console.warn(`! Could not parse ${path}: ${(err as Error).message}`);
    return fallback;
  }
}

export async function writeJson(path: string, value: unknown): Promise<void> {
  await writeFile(path, JSON.stringify(value, null, 2) + "\n", "utf8");
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

export function renderDigest(queue: Candidate[], nowIso: string): string {
  const pending = queue.filter((c) => c.status === "pending_review");
  const approved = queue.filter((c) => c.status === "approved");
  const lines: string[] = [];
  lines.push("# Corpus review queue");
  lines.push("");
  lines.push(
    "> Auto-generated by `@platform/corpus-watch`. New auto-readable content (YouTube)",
  );
  lines.push(
    "> is **promoted into `corpus/sources.seed.json` automatically** each cycle, inheriting",
  );
  lines.push(
    "> the parent creator's safety guardrails. Instagram / TikTok can't be auto-read, so",
  );
  lines.push(
    "> they appear below as manual checks. To pause auto-promotion and gate it behind",
  );
  lines.push(
    "> human approval, set `CORPUS_PROMOTE_REQUIRE_APPROVAL=1` and approve with `npm run approve`.",
  );
  lines.push("");
  lines.push(
    `Last scan: ${nowIso} · ${pending.length} pending · ${approved.length} approved (awaiting promote)`,
  );
  lines.push("");

  const auto = pending.filter((c) => !c.needs_manual_check);
  const manual = pending.filter((c) => c.needs_manual_check);

  if (approved.length) {
    lines.push("## Approved — will be added on next promote");
    lines.push("");
    for (const c of approved)
      lines.push(`- ${c.source_name}: ${escapeCell(c.content_title)}`);
    lines.push("");
  }

  if (auto.length) {
    lines.push("## New content (auto-promoting)");
    lines.push("");
    lines.push("| Discovered | Creator | Title | Link | Published |");
    lines.push("|---|---|---|---|---|");
    for (const c of auto) {
      lines.push(
        `| ${c.discovered_at.slice(0, 10)} | ${c.source_name} | ${escapeCell(
          c.content_title,
        )} | [open](${c.content_url}) | ${c.published_at?.slice(0, 10) ?? "—"} |`,
      );
    }
    lines.push("");
  }

  if (manual.length) {
    lines.push("## Manual checks (Instagram / TikTok — not auto-pollable)");
    lines.push("");
    for (const c of manual) {
      lines.push(`- [ ] ${c.source_name} — [${c.content_url}](${c.content_url})`);
    }
    lines.push("");
  }

  if (!approved.length && !auto.length && !manual.length) {
    lines.push("_Nothing pending. Queue is clear._");
    lines.push("");
  }
  return lines.join("\n");
}
